ckr344/freemarket_sample_63b

- app/models/category.rb
- db/migrate/20200215133049_category.rb
- db/migrate/20200216121317_create_categories.rb
- db/schema.rb
- test/fixtures/categories.yml
categoryのテーブル、モデル修正
記述ミスがみられたため
> [WIP]category_tableの修正

- README.md
- app/models/transaction.rb
- db/migrate/20200217112047_create_transactions.rb
- db/schema.rb
- test/fixtures/transactions.yml
- test/models/transaction_test.rb
Transaction(取引)テーブルの作成した。
カラムを追加し、アソシエーションの設定を行った。
Transactionテーブルは本アプリケーションの根幹機能となる為。
> Transactionテーブルの実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/product/show.scss
- app/views/products/show.html.haml
商品(Product)詳細ページ(show action)のフロント実装をした。
商品詳細ページは本アプリケーションの必須画面となる為。
> 商品詳細ページのフロント実装

- app/controllers/application_controller.rb
　application_controller.rbを編集
ストロングパラメーター実装のため
> strong　parameter

- app/assets/stylesheets/_header.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/categories.scss
- app/views/categories/index.html.haml
カテゴリー一覧ページの実装
カテゴリー別で検索する際に必要だから
> [WIP]categoryViewのhamlとcssの実装

- db/migrate/20200223112828_categories_ancestry.rb
- db/schema.rb
ancestryGemのためのマイグレーションファイルの作成
ancestryGemを使用するためにマイグレーションファイルが必要と思ったから
> [WIP]ancestryGemを使用するためのマイグレーションファイルの作成

- app/models/maincategory.rb
- db/migrate/20200223112828_categories_ancestry.rb
- db/migrate/20200224084308_create_maincategories.rb
- db/migrate/20200224084522_add_ancestry_to_maincategory.rb
- db/seeds.rb
---
カテゴリー一覧に使うseedの作成
元々あったマイグレーションファイルを削除
---
カテゴリーは後から追加、変更が少ないためseedを用いた
元々あったマイグレーションファイルだと齟齬が生じたのとファイル名が適切でなかったため
> [WIP]カテゴリー一覧のためのseedの追加

- db/migrate/20200224120458_add_ancestry_to_category.rb
- db/schema.rb
- db/seeds.rb
---
category用のseedの編集、およびseed用のマイグレーションファイルを作成
---
編集前のcategory seedだと現在存在しないmaincategoryにカテゴリーデータが保存されてしまうので、保存先をcategoryになるように変更を施した。
マイグレーションファイルはseedには必要であるため追加
> [WIP]Category一覧のためのseed作成およびマイグレーションファイルの作成

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/user/new.scss
- app/views/devise/registrations/new.html.haml
ユーザー登録画面の実装
[![Image from Gyazo](https://i.gyazo.com/90155e79bfdb542585fe133ec3d8fd5f.png)](https://gyazo.com/90155e79bfdb542585fe133ec3d8fd5f)
[![Image from Gyazo](https://i.gyazo.com/62516d32c67e05c0a62c32322102cb3b.png)](https://gyazo.com/62516d32c67e05c0a62c32322102cb3b)
ユーザー登録に必要であるため。
> [WIP]user登録画面view

- README.md
- db/migrate/20200215072207_create_images.rb
- db/schema.rb
Imageモデルに紐付くProductのIDをinteger型からreferences型に変更した
Imageは必ずProductに紐付くため
> [WIP]Imageモデルに紐付くProductのIDをreferences型に変更

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/product/new.scss
- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/new.html.haml
- db/migrate/20200214105802_create_products.rb
- db/schema.rb
各データを保存し、出品する機能を実装
フリマにおける必須事項
> [WIP]出品機能の実装

- Gemfile
- Gemfile.lock
- app/assets/javascripts/payjp.js
- app/controllers/cards_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.haml
gonというGemを用いて、クレジットカード登録の際のJSに直接公開鍵が表示されないように修正した。
セキュリティを上げるため
> [WIP]gonを用いてクレジットカード登録を修正

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/user/registration/new.scss
- app/assets/stylesheets/user/sessions/new.scss
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
ユーザー登録、ログイン画面ビュー
[![Image from Gyazo](https://i.gyazo.com/667ec02c6d3a45a020c1eb35dbc7bbcf.png)](https://gyazo.com/667ec02c6d3a45a020c1eb35dbc7bbcf)
ユーザー登録、ログインに必要であるため。
※ローカルでheader footerが消える元凶となった部分は削除してあります。
> [WIP]ユーザー登録、ログイン画面ビュー

- Gemfile
- Gemfile.lock
gemfile「ransack」のインストール
検索機能の実装を簡単にするため
> gemfile 'ransack'のインストール

- Gemfile.lock
- app/controllers/products_controller.rb
- app/views/layouts/application.html.haml
- app/views/products/show.html.haml
出品した商品を出品者のみが削除できるようにした
必須機能であるため
> [WIP]商品削除機能の実装

- app/assets/stylesheets/product/show.scss
- app/assets/stylesheets/transaction/pay_index.scss
- app/controllers/products_controller.rb
- app/controllers/transactions_controller.rb
- app/views/products/show.html.haml
- app/views/transactions/done.html.haml
- app/views/transactions/pay_index.html.haml
商品詳細画面から購入→完了までの画面に実際のデータを変数を用いて反映させた。
必須情報となるため。
> [WIP]商品詳細画面から購入→完了までの実装

- Gemfile
- Gemfile.lock
- spec/controllers/products_controller_spec.rb
controllerテストに必要なgemとproducts_controller_spec.rbの雛形作成
必須事項であるため
バッティング防止のため一応ブランチきりました
> [WIP]controllerテストの下準備

- Gemfile
- Gemfile.lock
- app/controllers/products_controller.rb
- app/models/transaction.rb
- spec/controllers/products_controller_spec.rb
- spec/factories/categories.rb
- spec/factories/products.rb
- spec/factories/transactions.rb
- spec/factories/users.rb
- spec/rails_helper.rb
> [WIP]Products controllerのテストコード（edit）

- app/assets/javascripts/product/new.js
- app/models/product.rb
- app/views/products/new.html.haml
- spec/models/product_spec.rb
各カラムに対するテスト
validatesの見直し
予期せぬバグ等を防止するため
> [WIP] Product_modelの修正とテストコード

- app/controllers/products_controller.rb
- app/views/layouts/_header.html.haml
ヘッダーのロゴをroot pathに変更した
ホーム画面に戻れないと操作性が悪いため
> [WIP]ヘッダーのロゴをroot pathに変更

- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/edit.html.haml
- app/views/products/new.html.haml
- app/views/products/show.html.haml
・商品出品→カテゴリーの保存ができない
・商品編集→手数料と利益がもともと表示されていない
上記２点の修正するにあたってviewファイルやmodelの変更
必須事項
> Productまわりの細かな修正

- app/assets/stylesheets/product/index.scss
- app/controllers/products_controller.rb
- app/views/products/index.html.haml
1. トップページのカテゴリー別商品表示
2. 商品詳細画面への移行
完成の条件となるため
[![Image from Gyazo](https://i.gyazo.com/bddfb8f454dc62a499fbc56f3caaa6a8.gif)](https://gyazo.com/bddfb8f454dc62a499fbc56f3caaa6a8)
> [WIP]トップページのカテゴリー別商品表示と商品詳細画面への移行

- app/controllers/products_controller.rb
- app/models/product.rb
- app/models/user.rb
- app/views/products/show.html.haml
- db/migrate/20200214105802_create_products.rb
- db/schema.rb
Transaction関係のアソシエーション・カラムを修正した。
デプロイ時にエラーが出たため。
> [WIP]Transaction関係のアソシエーション修正

- app/controllers/products_controller.rb
- app/models/product.rb
- spec/helpers/transactions_helper_spec.rb
- spec/models/product_spec.rb
商品編集機能のテストコードを実装した
Transactionのテストコードは現在実装中のためPending
Productモデルのバリデーションを一部修正
完成の定義に含まれるため
[![Image from Gyazo](https://i.gyazo.com/c36182e5daa1eed0388a6f084803876b.png)](https://gyazo.com/c36182e5daa1eed0388a6f084803876b)
> [WIP]商品編集機能のテストコード

- app/controllers/products_controller.rb
- app/models/product.rb
- app/models/user.rb
アソシエーションを一部修正
本番環境でProductが削除できない原因はこちらでした
削除機能は必須であるため
> [WIP]アソシエーションを修正

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/user/show.scss
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/_header.html.haml
- app/views/users/show.html.haml
- config/routes.rb
・マイページの実装、マイページからのログアウト機能
・ヘッダー修正。ヘッダーから新規登録、ログイン画面への移行
https://gyazo.com/7dba31953c7eb7ff5f6a25c1419e706e
https://gyazo.com/63892b1e2574ed72573ee532efdc7414
ユーザー管理に必要であるため。
> [WIP] マイページの実装、ヘッダーの修正

- app/assets/javascripts/product/new.js
- app/assets/stylesheets/product/new.scss
- app/controllers/products_controller.rb
- app/controllers/transactions_controller.rb
- app/uploaders/image_uploader.rb
- app/views/products/edit.html.haml
- app/views/products/index.html.haml
- app/views/products/new.html.haml
- config/environments/production.rb
①商品編集のカテゴリー取得と変更
②Transactionアクション修正
③画像Uploadサイズ変更
④トップページビュー崩れ修正
スプリントレビューの指摘箇所を修正しました
> [WIP]商品編集のカテゴリー取得と変更、Transactionアクション修正、画像Uploadサイズ変更、トップページビュー崩れ修正

- app/assets/javascripts/product/new.js
詳細画面にて、画像をタップした際に、その画像がトップに表示されるようにした
実用性が上がるため
> [WIP]商品詳細画面js追加

- app/assets/javascripts/registration.js
- app/views/devise/registrations/new.html.haml
ユーザー登録画面で誕生日の入力をJSで実装した。
[![Image from Gyazo](https://i.gyazo.com/ffbfca7bd27d1070368190b414705c1c.gif)](https://gyazo.com/ffbfca7bd27d1070368190b414705c1c)
誕生日の入力を容易にするため。
> [WIP]ユーザー登録画面　誕生日JS入力

- app/assets/stylesheets/user/registration/new.scss
ユーザー登録画面　エラー時ビュー崩れ修正
[![Image from Gyazo](https://i.gyazo.com/43897766308ab70005220ce4b8173083.png)](https://gyazo.com/43897766308ab70005220ce4b8173083)
エラー時にビューが崩れるため。
> [WIP]ユーザー登録画面　エラー時ビュー崩れ修正

- Gemfile
- Gemfile.lock
- spec/models/user_spec.rb
ユーザー登録機能のテストのため 
ユーザー機能が正しく機能しているか確認するため
> [WIP]ユーザーテスト

- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/devise/sessions/new.html.haml
商品出品・編集のバリデーションを修正を修正した
必須項目が入力されていなかった場合はnew, editアクションにそれぞれredirectされるようにした
エラー回避のため
> [WIP]商品出品・編集のバリデーションを修正

- app/models/transaction.rb
- spec/factories/transactions.rb
- spec/models/transaction_spec.rb
Transaction単体テスト
[![Image from Gyazo](https://i.gyazo.com/16bde7f375a427e57f29e2f3c55b47a1.png)](https://gyazo.com/16bde7f375a427e57f29e2f3c55b47a1)
購入機能の確認に必要であるため。
> [WIP]Transaction単体テスト
